# fly.toml app configuration file generated for hoteratus2 on 2024-02-12T19:35:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hoteratus2'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '20'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://csa.trypid.com'
  LOG_CHANNEL = 'stack'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  CACHE_DRIVER = "redis"
  SESSION_DRIVER = "redis"
  REDIS_HOST = "hoteratus-redis.internal"
  DB_CONNECTION = "mysql"
  DB_HOST = "hoteratus-mysql.internal"
  QUEUE_CONNECTION="redis"
  DB_DATABASE= "hoteratus"
  SCRAPER_NODE_PATH="/usr/bin/node"
  SCRAPER_CHROME_PATH="/usr/bin/google-chrome"

[processes]
  app = ''
  cron = 'cron -f'
  worker = 'php artisan queue:listen'

[[mounts]]
  source = 'storage_volume'
  destination = '/var/www/html/storage'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app', 'cron', 'worker']

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"
