# fly.toml app configuration file generated for hoteratus-mysql on 2024-02-16T17:58:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hoteratus-mysql'
primary_region = 'lhr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
